name: Sign_in
main: com.chenhao220.Signin.Signin
version: 1.0 Release
author: chenhao220
commands: 
  signin:
    description: signin main commands
    usage: /<command>
    permission: signin.main
    permission-message: §c你需要sigin.main权限来执行此命令
permissions: 
  signin.main: 
    description: 允许使用/sign
    default: true
  signin.reload:
    description: 允许重载配置文件
    default: op